# global section is used for the default settings (admin overrides are currently not supported).
[global]
  # seo_robots_txt is served for HTTP GET requests to the /robots.txt path
  seo_robots_txt = "Allow: *\n"
