kind: ProductPriceGroup
productPriceGroup:
  currency: GBP
  products:
    - product:
        code: standardJobListing
        price: 49.96
        title: Standard Job List
        description: A standard job post listing.
    - product:
        code: standardHighlight
        price: 35.46
        title: Standard Highlight
        description: Standard colour highlight.
    - product:
        code: customHighlight
        price: 35.46
        title: Custom Highlight
        description: Use your personal brand colours to match you job listing.
